BiblotekaWeb/Areas/admin/Models/Libri.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Http;

#nullable disable

namespace BiblotekaWeb.Areas.admin.Models
{
    public partial class Libri
    {
        public Libri()
        {
            Aktivitetis = new HashSet<Aktiviteti>();
            Gjobas = new HashSet<Gjoba>();
            Huazimis = new HashSet<Huazimi>();
        }

       
        public string LibriId { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Kjo fushë është e obligueshme")]
        public string Titulli { get; init; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Kjo fushë është e obligueshme")]
        public string Autori { get; init; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Kjo fushë është e obligueshme")]
        public string Botuesi { get; init; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Selektoni Gjuhën")]
        public int GjuhaId { get; init; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Selektoni Kategorinë")]
        public int KategoriaId { get; init; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Kjo fushë është e obligueshme")]
        public string Isbn { get; init; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Kjo fushë është e obligueshme")]
        public string Editioni { get; init; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Kjo fushë është e obligueshme")]
        public int NumriKopjeve { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Kjo fushë është e obligueshme")]
        public bool Statusi { get; set; }
        public string ImageName { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Kjo fushë është e obligueshme")]
        [NotMapped]
        public IFormFile Image { get; init; }
        public int InsertBy { get; set; }
        public DateTime? InsertDate { get; set; }
        public int? Lub { get; set; }
        public int? Lun { get; set; }
        public DateTime? Lud { get; set; }

        public virtual Gjuha Gjuha { get; set; }
        public virtual Kategorium Kategoria { get; set; }
        public virtual ICollection<Aktiviteti> Aktivitetis { get; set; }
        public virtual ICollection<Gjoba> Gjobas { get; set; }
        public virtual ICollection<Huazimi> Huazimis { get; set; }
    }
}

BiblotekaWeb/Areas/admin/Controllers/LibriController.cs
using System;
using System.IO;
using AspNetCoreHero.ToastNotification.Abstractions;
using BiblotekaWeb.Areas.admin.Data;
using BiblotekaWeb.Areas.admin.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using ClosedXML.Excel;
using Dapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Rotativa.AspNetCore;

namespace BiblotekaWeb.Areas.admin.Controllers
{
    [Area("admin")]
    [Authorize(Roles = "Administrator,Punëtor")]
    public class LibriController : Controller
    {
        private IConfiguration Config { get; }
        private IWebHostEnvironment HostEnvironment { get; }
        private readonly ILibriService _libriService;
        private readonly INotyfService _notyfi;
        private readonly BiblotekaWebContext _webContext;

        public LibriController(ILibriService libriService, 
                            INotyfService notyf,
                            BiblotekaWebContext webContext,
                            IConfiguration _config,
                            IWebHostEnvironment hostEnvironment)
        {
            Config = _config;
            HostEnvironment = hostEnvironment;
            _libriService = libriService;
            _notyfi = notyf;
            _webContext = webContext;
        }

        public IActionResult Index()
        {
            var librat = _libriService.GetAllLibri();
            return View(librat); 
        }


        [HttpGet]
        public IActionResult Shto()
        {
            ViewBag.Kategorite = _webContext.Kategoria.ToList();
            ViewBag.Gjuhet = _webContext.Gjuhas.ToList();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Shto(Libri libri)
        {
            var id = string.Empty;
            await using (var con = new SqlConnection(Config.GetConnectionString("Conn")))
            {
                id = con.Query<string>("select dbo.LibriID()").FirstOrDefault();
            }
            var wwwRootPath = HostEnvironment.WebRootPath;
            var fileName = libri.Titulli.ToLower() + DateTime.Now.ToString("ddMMyyyy");
            var exts = Path.GetExtension(libri.Image.FileName);
            fileName = fileName.Replace(" ", string.Empty) + exts;
            var path = Path.Combine(wwwRootPath + "/Admin/img/bookImages", fileName);
            await using (var fileStream = new FileStream(path, FileMode.Create))
                await libri.Image.CopyToAsync(fileStream);
            libri.ImageName = fileName;
            libri.InsertBy = Convert.ToInt32(User.Claims.ElementAt(1).Value);
            libri.LibriId = id;
            libri.InsertDate = DateTime.Now;
            _libriService.ShtoLibrin(libri);
            _notyfi.Custom("Libri u shtua!", 5, "#FFBC53", "fa fa-check");
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Edito(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            ViewBag.Kategorite = _webContext.Kategoria.ToList();
            ViewBag.Gjuhet = _webContext.Gjuhas.ToList();
            var libri = _libriService.GetLibriById(id);
            return View(libri);
        }

        [HttpPost]
        public IActionResult Edito(string id,Libri libri)
        {
            var liber = _libriService.GetLibriById(id);
            if (liber.Lun == null)
                libri.Lun = 1;
            else
                libri.Lun = liber.Lun + 1;
            libri.Lub = Convert.ToInt32(User.Claims.ElementAt(1).Value);
            libri.Lud = DateTime.Now;
            libri.LibriId = id;
            libri.InsertBy = liber.InsertBy;
            libri.InsertDate = liber.InsertDate;
            libri.ImageName = liber.ImageName;
            _libriService.PerditesoLibrin(libri);
            _notyfi.Custom("Libri u përditësua!", 5, "#FFBC53", "fa fa-check");
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [Route("admin/libri/delete/{id}")]
        public IActionResult Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var libri = _libriService.GetLibriById(id);
            var imgName = libri.ImageName;
            var result = _libriService.DeleteLibrin(id);
            if (!result) return Json(result);
            var wwwRootPath = HostEnvironment.WebRootPath;
            var path = Path.Combine(wwwRootPath + "/Admin/img/bookImages", imgName);
            if (System.IO.File.Exists(path)) System.IO.File.Delete(path);
            return Json(result);
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Print()
        {
            const string footer = "--footer-center \"Copyright © 2021 Library Management System.  Page: [page]/[toPage]\"" + " --footer-line --footer-font-size \"10\" --footer-font-name \"Poppins light\"";
            var stafiId = Convert.ToInt32(User.Claims.First(x => x.Type == "Id").Value);
            var stafi = _webContext.Stafis.Single(x => x.StafiId == stafiId);
            ViewData["Stafi"] = stafi.Emri + " " + stafi.Mbiemri;
            return new ViewAsPdf(_libriService.GetAllLibri(), ViewData)
            {
                CustomSwitches = footer
            };
        }

        public IActionResult Export() => Excel();

        public IActionResult Excel()
        {
            var librat = _libriService.GetAllLibri();
            using var workbook = new XLWorkbook();
            var worksheet = workbook.Worksheets.Add("Librat");
            var currentRow = 1;
            worksheet.Cell(currentRow, 1).Value = "LibriID";
            worksheet.Cell(currentRow, 2).Value = "Titulli";
            worksheet.Cell(currentRow, 3).Value = "Autori";
            worksheet.Cell(currentRow, 4).Value = "Botuesi";
            worksheet.Cell(currentRow, 5).Value = "Gjuha";
            worksheet.Cell(currentRow, 6).Value = "Kategoria";
            worksheet.Cell(currentRow, 7).Value = "Editioni";
            worksheet.Cell(currentRow, 8).Value = "Sasia";
            worksheet.Cell(currentRow, 9).Value = "Statusi";

            IXLRange range = worksheet.Range(worksheet.Cell(currentRow, 1).Address,
                worksheet.Cell(currentRow, 9).Address);
            range.Style.Font.Bold = true;
            range.Style.Border.OutsideBorder = XLBorderStyleValues.Medium;
            worksheet.ColumnWidth = 20;
            foreach (var liber in librat)
            {
                currentRow++;
                worksheet.Cell(currentRow, 1).Value = liber.LibriId;
                worksheet.Cell(currentRow, 2).Value = liber.Titulli;
                worksheet.Cell(currentRow, 3).Value = liber.Autori;
                worksheet.Cell(currentRow, 4).Value = liber.Botuesi;
                worksheet.Cell(currentRow, 5).Value = liber.Gjuha.Emertimi;
                worksheet.Cell(currentRow, 6).Value = liber.Kategoria.Emertimi;
                worksheet.Cell(currentRow, 7).Value = liber.Editioni;
                worksheet.Cell(currentRow, 8).Value = liber.NumriKopjeve;
                worksheet.Cell(currentRow, 9).Value = liber.Statusi ? "Aktiv" : "Joaktiv";
            }
            using var stream = new MemoryStream();
            workbook.SaveAs(stream);
            var content = stream.ToArray();
            return File(content, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                "Librat.xlsx");
        }
    }
}

BiblotekaWeb/Areas/admin/Views/Libri/Detalet.cshtml
@model BiblotekaWeb.Areas.admin.Models.Libri

@{
    ViewData["Title"] = "Detalet";
}

<h1>Detalet</h1>

<h4>Libri</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LibriId" class="control-label"></label>
                <input asp-for="LibriId" class="form-control" />
                <span asp-validation-for="LibriId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Titulli" class="control-label"></label>
                <input asp-for="Titulli" class="form-control" />
                <span asp-validation-for="Titulli" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Autori" class="control-label"></label>
                <input asp-for="Autori" class="form-control" />
                <span asp-validation-for="Autori" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Botuesi" class="control-label"></label>
                <input asp-for="Botuesi" class="form-control" />
                <span asp-validation-for="Botuesi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gjuha" class="control-label"></label>
                <input asp-for="Gjuha" class="form-control" />
                <span asp-validation-for="Gjuha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KategoriaId" class="control-label"></label>
                <input asp-for="KategoriaId" class="form-control" />
                <span asp-validation-for="KategoriaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Editioni" class="control-label"></label>
                <input asp-for="Editioni" class="form-control" />
                <span asp-validation-for="Editioni" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumriKopjeve" class="control-label"></label>
                <input asp-for="NumriKopjeve" class="form-control" />
                <span asp-validation-for="NumriKopjeve" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Isbn" class="control-label"></label>
                <input asp-for="Isbn" class="form-control" />
                <span asp-validation-for="Isbn" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Statusi" /> @Html.DisplayNameFor(model => model.Statusi)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Ruaj" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Kthehu te Lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BiblotekaWeb/Areas/admin/Views/Libri/Edito.cshtml
@model BiblotekaWeb.Areas.admin.Models.Libri

@{
    ViewData["Title"] = "Edito";
}

<div class="page-wrapper">
    <div class="content container-fluid">
        <div class="page-header">
            <div class="row align-items-center">
                <div class="col">
                    <h3 class="page-title">Edito Libër</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a asp-action="Index">Librat</a></li>
                        <li class="breadcrumb-item active">Edito Libër</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <form asp-action="Edito">
                            <div class="row">
                                <div class="col-12">
                                    <h5 class="form-title"><span>Informatat e Librit</span></h5>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                        <label>Titulli</label>
                                        <input asp-for="Titulli" class="form-control">
                                        <span asp-validation-for="Titulli"></span>
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                        <label>Autori</label>
                                        <input asp-for="Autori" class="form-control">
                                        <span asp-validation-for="Autori"></span>
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                        <label>Botuesi</label>
                                        <input asp-for="Botuesi" class="form-control">
                                        <span asp-validation-for="Botuesi"></span>
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                        <label>Gjuha</label>
                                        <select asp-for="GjuhaId" asp-items="@(new SelectList(ViewBag.Gjuhet,"GjuhaId","Emertimi"))" class="form-control">
                                            <option>Selekto Gjuhën</option>
                                        </select>
                                        <span asp-validation-for="GjuhaId"></span>
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                        <label>Kategoria</label>
                                        <select asp-for="KategoriaId" asp-items="@(new SelectList(ViewBag.Kategorite, "KategoriaId", "Emertimi"))" class="form-control">
                                            <option>Selekto Kategorinë</option>
                                        </select>
                                        <span asp-validation-for="KategoriaId"></span>
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                        <label>ISBN</label>
                                        <input asp-for="Isbn" min="0" class="form-control">
                                        <span asp-validation-for="Isbn"></span>
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                        <label>Editioni</label>
                                        <input asp-for="Editioni" min="0" class="form-control">
                                        <span asp-validation-for="Editioni"></span>
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                        <label>NumriKopjeve</label>
                                        <input asp-for="NumriKopjeve" min="0" class="form-control">
                                        <span asp-validation-for="NumriKopjeve"></span>
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                        <label>Statusi</label>
                                        <select asp-for="Statusi" class="form-control">
                                            <option value="true">Aktiv</option>
                                            <option value="false">Joaktiv</option>
                                        </select>
                                        <span asp-validation-for="Statusi"></span>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <button type="submit" class="btn btn-primary">Edito</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BiblotekaWeb/Areas/admin/Views/Libri/Index.cshtml
@model IEnumerable<BiblotekaWeb.Areas.admin.Models.Libri>

@{
    ViewData["Title"] = "Lista e Librave";
}

<div class="page-wrapper">
    <div class="content container-fluid">
        <div class="page-header">
            <div class="row align-items-center">
                <div class="col">
                    <h3 class="page-title">Librat</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Ballina</a></li>
                        <li class="breadcrumb-item active">Librat</li>
                    </ul>
                </div>
                <div class="col-auto text-right float-right ml-auto">
                    <a asp-action="Export" class="btn btn-outline-primary mr-2"><i class="fas fa-download"></i> Shkarko</a>
                    <a asp-action="Print" target="_blank" class="btn btn-outline-primary mr-2"><i class="fas fa-print"></i> Printo</a>
                    <a asp-controller="Libri" asp-action="Shto" class="btn btn-primary"><i class="fas fa-plus"></i></a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="card card-table">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="dataTable" class="table table-hover table-center mb-0 ">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Titulli</th>
                                    <th>Autori</th>
                                    <th>Botuesi</th>
                                    <th>Gjuha</th>
                                    <th>Kategoria</th>
                                    <th>Editioni</th>
                                    <th>ISBN</th>
                                    <th>Sasia</th>
                                    <th>Statusi</th>
                                    <th class="text-right">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach (var liber in Model)
                                {
                                    <tr>
                                        <td>@liber.LibriId</td>
                                        <td>
                                            <h2>
                                                <a>@liber.Titulli</a>
                                            </h2>
                                        </td>
                                        <td>@liber.Autori</td>
                                        <td>@liber.Botuesi</td>
                                        <td>@liber.Gjuha.Emertimi</td>
                                        <td>@liber.Kategoria.Emertimi</td>
                                        <td>@liber.Editioni</td>
                                        <td>@liber.Isbn</td>
                                        <td>@liber.NumriKopjeve</td>
                                        @if (liber.Statusi)
                                        {
                                            <td>
                                                <span class="badge badge-success">Aktiv</span>
                                            </td>
                                        }
                                        else
                                        {
                                            <td>
                                                <span class="badge badge-danger">Joaktiv</span>
                                            </td>
                                        }
                                        <td class="text-right">
                                            <div class="actions">
                                                <a asp-action="Edito" asp-route-id="@liber.LibriId" class="btn btn-sm bg-success-light mr-2">
                                                    <i class="fas fa-pen"></i>
                                                </a>
                                                <a onclick="showPopUp('@liber.LibriId')" class="btn btn-sm bg-danger-light">
                                                    <i class="fas fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer>
        <p>Copyright © 2021 Menaxhimi Biblotekës.</p>
    </footer>
</div>


<script type="text/javascript">
function showPopUp(libriId) {
        window.Swal.fire({
            title: 'A jeni i sigurtë?',
            text: "Nuk mund ta ktheni këtë hap!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Po, fshije!',
            cancelButtonText: 'Anulo'
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({
                    type: "POST",
                    url: "/admin/libri/delete/" + libriId,
                    data: libriId,
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function (data) {
                        if (data === true) {
                            window.Swal.fire(
                                'U Fshi!',
                                'Rekordi është fshirë.',
                                'success'
                            ).then((result) => {
                                if (result.isConfirmed) {
                                    location.reload();
                                }
                            });
                        }
                        if (data === false){
                            window.Swal.fire({
                                  icon: 'error',
                                  title: 'Oops...',
                                  text: 'Ky libër nuk mundë të fshihet',
                                  footer: '<a href="">Pse është ky gabim?</a>'
                                })
                        }
                    },
                })
           }
        })
    }
</script>

BiblotekaWeb/Areas/admin/Views/Libri/Print.cshtml
@model IEnumerable<BiblotekaWeb.Areas.admin.Models.Libri>

@{
    ViewData["Title"] = "Raporti i Librave";
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,500;0,600;0,700;1,400&amp;display=swap">
    <link rel="stylesheet" href="~/Admin/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Admin/css/style.css">
</head>
<body>
<h1 class="text-center">Lista e Librave</h1>
<h4 style="margin-top: 100px;">Data: @DateTime.Now.ToString("dd/MM/yyyy hh:mm:ss")</h4>
<h4>Gjeneruar Nga: @ViewData["Stafi"]</h4>
<table class="table" style="margin-top: 50px;">
    <thead>
    <tr>
        <th>ID</th>
        <th>Titulli</th>
        <th>Autori</th>
        <th>Botuesi</th>
        <th>Gjuha</th>
        <th>Kategoria</th>
        <th>Editioni</th>
        <th>Sasia</th>
        <th>Statusi</th>
    </tr>
    </thead>
    <tbody>
    @if (!Model.Any())
    {
        <tr class="text-center">
            <td colspan="8">
                <span>Nuk ka Libra të regjistruar!</span>
            </td>
        </tr>
    }
    else
    {
        @foreach (var liber in Model)
        {
            <tr>
                <td>@liber.LibriId</td>
                <td>
                    <h2 class="table-avatar">
                        <a>@liber.Titulli</a>
                    </h2>
                </td>
                <td>@liber.Autori</td>
                <td>@liber.Botuesi</td>
                <td>@liber.Gjuha.Emertimi</td>
                <td>@liber.Kategoria.Emertimi</td>
                <td>@liber.Editioni</td>
                <td>@liber.NumriKopjeve</td>
                @if (liber.Statusi)
                {
                    <td>
                        <span class="badge badge-success">Aktiv</span>
                    </td>
                }
                else
                {
                    <td>
                        <span class="badge badge-danger">Joaktiv</span>
                    </td>
                }
            </tr>
        }
    }
    </tbody>
</table>
<p class="mt-2 text-right">Total Libra: @Model.Count()</p>

<script src="~/Admin/js/jquery-3.5.1.min.js"></script>
<script src="~/Admin/js/popper.min.js"></script>
<script src="~/Admin/plugins/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>