BiblotekaWeb/Areas/admin/Models/Klienti.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace BiblotekaWeb.Areas.admin.Models
{
    public partial class Klienti
    {
        public Klienti()
        {
            Aktivitetis = new HashSet<Aktiviteti>();
            Gjobas = new HashSet<Gjoba>();
            Huazimis = new HashSet<Huazimi>();
        }

        public string KlientiId { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Kjo fushë është e obligueshme")]

        public string Emri { get; init; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Kjo fushë është e obligueshme")]
        public string Mbiemri { get; init; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Kjo fushë është e obligueshme")]
        [DataType(DataType.Date)]
        public DateTime Datalindjes { get; init; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Selektoni Gjininë")]
        public string Gjinia { get; init; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Kjo fushë është e obligueshme")]
        [MinLength(10,ErrorMessage = "Numri personal duhet të ketë 10 numra")]
        [MaxLength(10,ErrorMessage = "Numri personal duhet të ketë 10 numra")]
        public string NrPersonal { get; init; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Kjo fushë është e obligueshme")]
        public string NrKontaktues { get; init; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Kjo fushë është e obligueshme")]
        public string Adresa { get; init; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Kjo fushë është e obligueshme")]
        public string Qyteti { get; init; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Kjo fushë është e obligueshme")]
        public string Shteti { get; init; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Kjo fushë është e obligueshme")]
        public string KodiPostal { get; init; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Kjo fushë është e obligueshme")]
        [EmailAddress]
        public string Emaili { get; init; }
        public int? Huazimet { get; set; }
        public int InsertBy { get; set; }
        public DateTime? InsertDate { get; set; }
        public int? Lub { get; set; }
        public int? Lun { get; set; }
        public DateTime? Lud { get; set; }

        public virtual ICollection<Aktiviteti> Aktivitetis { get; set; }
        public virtual ICollection<Gjoba> Gjobas { get; set; }
        public virtual ICollection<Huazimi> Huazimis { get; set; }
    }
}

BiblotekaWeb/Areas/admin/Controllers/KlientiController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using AspNetCoreHero.ToastNotification.Abstractions;
using BiblotekaWeb.Areas.admin.Data;
using BiblotekaWeb.Areas.admin.Models;
using ClosedXML.Excel;
using Dapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Configuration;
using Rotativa.AspNetCore;

namespace BiblotekaWeb.Areas.admin.Controllers
{
    [Area("admin")]
    [Authorize(Roles = "Administrator,Punëtor")]
    public class KlientiController : Controller
    {
        private IConfiguration Configuration { get; }
        private readonly IKlientiService _klientiService;
        private readonly INotyfService _notyf;
        public KlientiController(IKlientiService klientiService,INotyfService notyf,IConfiguration configuration)
        {
            
            Configuration = configuration;
            _klientiService = klientiService;
            _notyf = notyf;
        }

        public IActionResult Index() => View(_klientiService.GetAllKlients());

        [HttpGet]
        public IActionResult Shto()
        {
            return View();
        }

        public IActionResult GetCities(string country)
        {
            var cities = country switch
            {
                "Kosovë" => BallinaData.GetCities(country),
                "Shqipëri" => BallinaData.GetCities(country),
                "Maqedoni" => BallinaData.GetCities(country),
                "Mali i Zi" => BallinaData.GetCities(country),
                _ => null
            };
            return Json(new {cities});
        }

        [HttpPost]
        public IActionResult Shto(Klienti klienti)
        {
            var klientiId = string.Empty;
            using (var con = new SqlConnection(Configuration.GetConnectionString("Conn")))
                klientiId = con.Query<string>("select dbo.KlientiID()").FirstOrDefault();
            if (!ModelState.IsValid) return View(klienti);
            klienti.KlientiId = klientiId;
            klienti.InsertBy = Convert.ToInt32(User.Claims.ElementAt(1).Value);
            klienti.InsertDate = DateTime.Now;
            _klientiService.ShtoKlient(klienti);
            _notyf.Custom("Klienti u shtua!", 5, "#FFBC53", "fa fa-check");
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Edito(string id)
        {       
            if (id == null)
            {
                return NotFound();
            }
            var klienti = _klientiService.GetKlientById(id);
            return View(klienti);
        }

        [HttpPost]
        public IActionResult Edito(string id, Klienti klienti)
        {
            if (!ModelState.IsValid) return View(klienti);
            var klient = _klientiService.GetKlientById(id);
            if (klient.Lun == null)
                klienti.Lun = 1;
            else
                klient.Lun++;
            klienti.Lub = Convert.ToInt32(User.Claims.ElementAt(1).Value);
            klienti.Lud = DateTime.Now;
            klienti.KlientiId = id;
            klienti.Huazimet = klient.Huazimet;
            klienti.InsertBy = klient.InsertBy;
            klienti.InsertDate = klient.InsertDate;
            _klientiService.PerditesoKlient(klienti);
            _notyf.Custom("Klienti u përditësua!", 5, "#FFBC53", "fa fa-check");
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var status = _klientiService.DeleteKlient(id);
            return Json(status);
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Print()
        {
            const string footer = "--footer-center \"Copyright © 2021 Library Management System.  Page: [page]/[toPage]\"" + " --footer-line --footer-font-size \"10\" --footer-font-name \"Poppins light\"";
            var stafiId = Convert.ToInt32(User.Claims.First(x => x.Type == "Id").Value);
            var stafi = _klientiService.GetStafi(stafiId);
            ViewData["Stafi"] = stafi.Emri + " " + stafi.Mbiemri;
            return new ViewAsPdf(_klientiService.GetAllKlients(), ViewData)
            {
                CustomSwitches = footer
            };
        }

        public IActionResult Export() => Excel();
        
        public IActionResult Excel()
        {
            var klientet = _klientiService.GetAllKlients();
            using var workbook = new XLWorkbook();
            var worksheet = workbook.Worksheets.Add("Klientët");
            var currentRow = 1;
            worksheet.Cell(currentRow, 1).Value = "KlientiID";
            worksheet.Cell(currentRow, 2).Value = "Emri";
            worksheet.Cell(currentRow, 3).Value = "Mbiemri";
            worksheet.Cell(currentRow, 4).Value = "NumriPersonal";
            worksheet.Cell(currentRow, 5).Value = "Emaili";
            worksheet.Cell(currentRow, 6).Value = "Adresa";
            worksheet.Cell(currentRow, 7).Value = "Huazimet";

            IXLRange range = worksheet.Range(worksheet.Cell(currentRow, 1).Address,
                worksheet.Cell(currentRow, 7).Address);
            range.Style.Font.Bold = true;
            range.Style.Border.OutsideBorder = XLBorderStyleValues.Medium;
            worksheet.ColumnWidth = 20;
            foreach (var klienti in klientet)
            {
                currentRow++;
                worksheet.Cell(currentRow, 1).Value = klienti.KlientiId;
                worksheet.Cell(currentRow, 2).Value = klienti.Emri;
                worksheet.Cell(currentRow, 3).Value = klienti.Mbiemri;
                worksheet.Cell(currentRow, 4).Value = klienti.NrPersonal;
                worksheet.Cell(currentRow, 5).Value = klienti.Emaili;
                worksheet.Cell(currentRow, 6).Value = klienti.Adresa;
                worksheet.Cell(currentRow, 7).Value = klienti.Huazimet;
            }
            using var stream = new MemoryStream();
            workbook.SaveAs(stream);
            var content = stream.ToArray();
            return File(content, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                "Klientët.xlsx");
        }
    }
}

BiblotekaWeb/Areas/admin/Views/Klienti/Edito.cshtml
@model BiblotekaWeb.Areas.admin.Models.Klienti

@{
    ViewData["Title"] = "Edito";
}

<div class="page-wrapper">
    <div class="content container-fluid">
        <div class="page-header">
            <div class="row align-items-center">
                <div class="col">
                    <h3 class="page-title">Edito Klientë</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a asp-action="Index">Klientët</a></li>
                        <li class="breadcrumb-item active">Edito Klientë</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <form asp-action="Edito">
                            <div class="row">
                                <div class="col-12">
                                    <h5 class="form-title"><span>Informatat e Klientit</span></h5>
                                </div>
                                <div asp-validation-summary="ModelOnly"></div>
                                <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                        <label>Emri</label>
                                        <input asp-for="Emri" class="form-control">
                                        <span asp-validation-for="Emri"></span>
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                        <label>Mbiemri</label>
                                        <input asp-for="Mbiemri" class="form-control">
                                        <span asp-validation-for="Mbiemri"></span>
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                        <label>Datalindjes</label>
                                        <input asp-for="Datalindjes" type="date" class="form-control">
                                        <span asp-validation-for="Datalindjes"></span>
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                        <label>Gjinia</label>
                                        <select asp-for="Gjinia" class="form-control">
                                            <option>Mashkull</option>
                                            <option>Femer</option>
                                        </select>
                                        <span asp-validation-for="Gjinia"></span>
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                        <label>NrPersonal</label>
                                        <input asp-for="NrPersonal" class="form-control">
                                        <span asp-validation-for="NrPersonal"></span>
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                        <label>Adresa</label>
                                        <input asp-for="Adresa" class="form-control">
                                        <span asp-validation-for="Adresa"></span>
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                        <label>Qyteti</label>
                                        <input asp-for="Qyteti" class="form-control">
                                        <span asp-validation-for="Qyteti"></span>
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                        <label>Shteti</label>
                                        <input asp-for="Shteti" class="form-control">
                                        <span asp-validation-for="Shteti"></span>
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                        <label>KodiPostal</label>
                                        <input asp-for="KodiPostal" class="form-control">
                                        <span asp-validation-for="KodiPostal"></span>
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                        <label>Numri Kontaktues</label>
                                        <input asp-for="NrKontaktues" class="form-control">
                                        <span asp-validation-for="NrKontaktues"></span>
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <div class="form-group">
                                        <label>Emaili</label>
                                        <input asp-for="Emaili" class="form-control">
                                        <span asp-validation-for="Emaili"></span>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <button type="submit" class="btn btn-primary">Edito</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BiblotekaWeb/Areas/admin/Views/Klienti/Index.cshtml
@model IEnumerable<BiblotekaWeb.Areas.admin.Models.Klienti>

@{
    ViewData["Title"] = "Klientët";
}

<div id="root" class="page-wrapper">
    <div class="content container-fluid">
        <div class="page-header">
            <div class="row align-items-center">
                <div class="col">
                    <h3 class="page-title">Klientët</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Ballina</a></li>
                        <li class="breadcrumb-item active">Klientët</li>
                    </ul>
                </div>
                <div class="col-auto text-right float-right ml-auto">
                    <a asp-action="Export" class="btn btn-outline-primary mr-2"><i class="fas fa-download"></i> Shkarko</a>
                    <a asp-action="Print" target="_blank" class="btn btn-outline-primary mr-2"><i class="fas fa-print"></i> Printo</a>
                    <a asp-action="Shto" asp-controller="Klienti" class="btn btn-primary"><i class="fas fa-plus"></i></a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="card card-table">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="dataTable" class="table table-hover table-center mb-0 ">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Emri</th>
                                    <th>Datalindjes</th>
                                    <th>NumriPersonal</th>
                                    <th>Adresa</th>
                                    <th>Qyteti</th>
                                    <th>Shteti</th>
                                    <th>Email</th>
                                    <th>Huazimet</th>
                                    <th class="text-right">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                    @foreach (var klient in Model)
                                    {
                                        <tr>
                                            <td>@klient.KlientiId</td>
                                            <td>
                                                <h2>
                                                    <a>@klient.Emri @klient.Mbiemri</a>
                                                </h2>
                                            </td>
                                            <td>@klient.Datalindjes.ToString("d")</td>
                                            <td>@klient.NrPersonal</td>
                                            <td>@klient.Adresa</td>
                                            <td>@klient.Qyteti</td>
                                            <td>@klient.Shteti</td>
                                            <td>@klient.Emaili</td>
                                            @if (klient.Huazimet == null)
                                            {
                                                <td>0</td>
                                            }
                                            else
                                            {
                                                <td>@klient.Huazimet</td>
                                            }
                                            <td class="text-right">
                                                <div class="actions">
                                                    <a asp-action="Edito" asp-route-id="@klient.KlientiId" class="btn btn-sm bg-success-light mr-2">
                                                        <i class="fas fa-pen"></i>
                                                    </a>
                                                    <a  onclick="showPopUp('@klient.KlientiId')" class="btn btn-sm bg-danger-light">
                                                        <i class="fas fa-trash"></i>
                                                    </a>
                                                </div>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer>
        <p>Copyright © 2021 Menaxhimi Biblotekës.</p>
    </footer>
</div>

<script type="text/javascript">
function showPopUp(klientiId) {
        window.Swal.fire({
            title: 'A jeni i sigurtë?',
            text: "Nuk mund ta ktheni këtë hap!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Po, fshije!',
            cancelButtonText: 'Anulo'
        }).then((result) => {
            if (result.isConfirmed) {
                console.log(klientiId);
                $.ajax({
                    type: "POST",
                    url: "/admin/klienti/delete/" + klientiId,
                    data: klientiId,
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function (data) {
                        if (data === true) {
                            window.Swal.fire(
                                'U Fshi!',
                                'Rekordi është fshirë.',
                                'success'
                            ).then((result) => {
                                if (result.isConfirmed) {
                                    location.reload();
                                }
                            });
                        }
                        if (data === false){
                            window.Swal.fire({
                                  icon: 'error',
                                  title: 'Oops...',
                                  text: 'Ky klient nuk mundë të fshihet',
                                  footer: '<a href="">Pse është ky gabim?</a>'
                                })
                        }
                    },
                });
            }
        });
    }
</script>

BiblotekaWeb/Areas/admin/Views/Klienti/Print.cshtml
@model IEnumerable<BiblotekaWeb.Areas.admin.Models.Klienti>

@{
    ViewBag.Title = "Raporti Klientëve";
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <title>@ViewData["Title"]</title>
    <link rel="shortcut icon" href="/favico.ico">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,500;0,600;0,700;1,400&amp;display=swap">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/Admin/plugins/bootstrap/css/bootstrap.min.css">
    <!-- Fontawesome CSS -->
    <!-- Main CSS -->
    <link rel="stylesheet" href="~/Admin/css/style.css">
</head>
<body>
<h1 class="text-center">Lista e Klientëve</h1>
<h4 style="margin-top: 100px;">Data: @DateTime.Now.ToString("dd/MM/yyyy hh:mm:ss")</h4>
<h4>Gjeneruar Nga: @ViewData["Stafi"]</h4>
<table class="table" style="margin-top: 50px;">
    <thead>
    <tr>
        <th>ID</th>
        <th>Emri</th>
        <th>Datalindjes</th>
        <th>NrPersonal</th>
        <th>Adresa</th>
        <th>Emaili</th>
        <th>Huazimet</th>
    </tr>
    </thead>
    <tbody>
    @if (!Model.Any())
    {
        <tr class="text-center">
            <td colspan="8">
                <span>Nuk ka Klientë të regjistruar!</span>
            </td>
        </tr>
    }
    else
    {
        @foreach (var klient in Model)
        {
            <tr>
                <td>@klient.KlientiId</td>
                <td>
                    <h2 class="table-avatar">
                        <a>@klient.Emri @klient.Mbiemri</a>
                    </h2>
                </td>
                <td>@klient.Datalindjes.ToString("dd/MM/yyyy")</td>
                <td>@klient.NrPersonal</td>
                <td>@klient.Adresa</td>
                <td>@klient.Emaili</td>
                <td>@klient.Huazimet</td>
            </tr>
        }
    }
    </tbody>
</table>
<p class="mt-2 text-right">Total Klientë: @Model.Count()</p>

<script src="~/Admin/js/jquery-3.5.1.min.js"></script>
<script src="~/Admin/js/popper.min.js"></script>
<script src="~/Admin/plugins/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>